### ISSUE TITLE
I found some typos, how do i submit them?

### ISSUE THREAD

**Issue by luzpaz** [qingfengxia/Cfd#15]
When I fork the repo it take me to https://github.com/luzpaz/CfdFoam which is a fork of https://github.com/jaheyns/CfdOF
So I can't make PRs to your repo.

**Comment by qingfengxia** [comment]
thanks, can you send pr to cfdfoam, they are more active , i am tangled
with job hunting.

On Saturday, 24 March 2018, luzpaz <notifications@github.com> wrote:
> When I fork the repo it take me to https://github.com/luzpaz/CfdFoam
which is a fork of https://github.com/jaheyns/CfdOF
> So I can't make PRs to your repo.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/fd66AC4aWVmz1rgv3Kbnt-oTgYt9tC0z4dQKPLuC7iJyfwAICDkcqtMF9qQ0KkYkQkq-rAUwdq5iUtKHlkNx6tt0UjyF4kO4PNywzpNkg_259KfnPLV24yNrJACTe49hk75vGk2crR6GwO2iiEAr4ZyevKg0Hw=s0-d-e1-ft#https://github.com/notifications/beacon/ADtnGwH0NBBv-HpvKOJn08yQ6x-mU_Bpks5thp6AgaJpZM4S53lO.gif
>

-- 
Qingfeng Xia

RA, Dept of Engineering, the University of Oxford
PhD Aerospace Engineering, the University of Manchester
