### ISSUE TITLE
No module named 'Units' initialization error

### ISSUE THREAD

**Issue by silopolis** [qingfengxia/Cfd#16]
Hi,

When starting Freecad (FreeCAD_0.18.15150_Conda_Py3Qt5_glibc2.12-x86_64.AppImage) I get the following error:

``During initialization the error No module named 'Units' occurred in /home/tarax/.FreeCAD/Mod/Cfd/InitGui.py``

**Comment by qingfengxia** [comment]
thank you for testing, QT5 is not tested, no mac handy, and I will test it
once QT5.12 released. xmas time

**Comment by qingfengxia** [comment]
This may due to error in import path. However, it disappeared in the latest git
